[package]
name = "hakase"
version = "0.1.0"
authors = ["Zeyi Fan <fanzeyi1994@gmail.com>"]
edition = "2021"

[dependencies]
gotham = "0.2.1"
gotham_derive = "0.2.1"
clap = "2.34.0"
hyper = "0.11.27"
mime = "0.3.17"
futures = "~0.1.31"
log = "0.4"
simplelog = "0.5.3"
serde = "1.0.219"
serde_derive = "1.0.219"
serde_urlencoded = "0.5.5"
diesel = { version = "2.2.10", features = ["mysql", "r2d2", "chrono"] }
r2d2 = "0.8.10"
rand = "0.5.6"
chrono = "0.4.41"
